trigger:
  branches:
    include:
    - data
pr:
  - data

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - script: sudo apt-get install -y jq
    displayName: 'Install JQ'
  - script: |
      shopt -s globstar
      cat repositories/* | jq '.'
    displayName: 'Run JQ'
